lastupdatecheck: 0
recentrepos:
- /home/brice/projects/nix
- /home/brice/projects/kucoin
- /home/brice/dotfiles/dev
- /home/brice/projects/zero2prod
- /home/brice/projects/zero2prod/
- /home/brice/projects/CV
- /home/brice/projects/Kaleidoscope
- /home/brice/dotfiles/master
- /home/brice/projects/cli-rust/catr
startuppopupversion: 5
customcommandshistory:
- git config pull.rebase true
hidecommandlog: false
ignorewhitespaceindiffview: false
